global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 10s
    static_configs:
      - targets: ['otel-collector:8889']

  - job_name: 'lpr-api'
    scrape_interval: 10s
    static_configs:
      - targets: ['lpr-api:8000']

  - job_name: 'customer-api'
    scrape_interval: 10s
    static_configs:
      - targets: ['customer-api:8001']